# **Tensorflow**

In [2]:
import tensorflow as tf
tf.__version__

'2.7.0'

### **A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.**

**Creating scalars and vectors with tf.constant()**

---



*   Can't be modified using tf.assign()


Tensor created with tf.constant() can't be modified using tf.assign()

In [3]:
scalar = tf.constant(10)
scalar

# scalar doesn't have any shape, i.e shape 0

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
vector = tf.constant([10,10]) # pass a list to create vector
vector

# vector will have shape

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# number of dimensions in vector
vector.ndim

1

**Creating a matrix**

In [6]:
matrix = tf.constant([[1,2,3],[4,2,1],[9,8,7]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 2, 1],
       [9, 8, 7]], dtype=int32)>

In [7]:
print(matrix.shape)
print(matrix.ndim)

(3, 3)
2


In [8]:
mat = tf.constant([[[1,2,3],[4,5,6]],[[4,3,6],[7,6,4]]],dtype=tf.float32) # write tf.float32 to specify datatype in dtype as parameter
print(mat.shape)
print(mat.ndim)
print(mat) # 3 dimensional matrix

(2, 2, 3)
3
tf.Tensor(
[[[1. 2. 3.]
  [4. 5. 6.]]

 [[4. 3. 6.]
  [7. 6. 4.]]], shape=(2, 2, 3), dtype=float32)


**Creating tensors with tf.Variable**

---



*   Can be modified using tf.assign()



In [9]:
vector = tf.Variable([1,2,3,4])
vector

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [10]:
vector[0].assign(7) # vector modified
vector

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([7, 2, 3, 4], dtype=int32)>

**tf.ones() and tf.zeros**

In [14]:
tf.ones(shape=[8,4],dtype=tf.int32) # pass the shape and datatype to create an array of ones

<tf.Tensor: shape=(8, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [15]:
tf.zeros(shape=[8,4],dtype=tf.double)

<tf.Tensor: shape=(8, 4), dtype=float64, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])>

### **Creating tensor from numpy array**

---

> The difference between a NumPy array and a tensor is that the tensors are backed by the accelerator memory like GPU and they are immutable, unlike NumPy arrays.

In [18]:
import numpy as np
arr=np.arange(1,50,dtype=np.float32)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49.], dtype=float32)

In [19]:
tf.constant(arr)

<tf.Tensor: shape=(49,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49.], dtype=float32)>

In [20]:
tf.Variable(arr)

<tf.Variable 'Variable:0' shape=(49,) dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49.], dtype=float32)>

### **Generating random tensors based on random seed**

---


*  A random seed specifies the start point when a computer generates a random number sequence. This can be any number, but it usually comes from seconds on a computer system’s clock (Henkemans & Lee, 2001).

*  tf.random.Generator creates a random number generator which gives us output based on distriutions specified.



In [12]:
random_generator = tf.random.Generator.from_seed(10)
tensor1=random_generator.normal(shape=(3,2))
tensor2=random_generator.uniform(shape=(4,3)) # these tensors are immutable, i.e tf.assign() can't be used 
print(tensor1)
print(tensor2)

tf.Tensor(
[[-0.29604465 -0.21134205]
 [ 0.01063002  1.5165398 ]
 [ 0.27305737 -0.29925638]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.8531755  0.3475517  0.609745  ]
 [0.54769015 0.29646897 0.8380779 ]
 [0.3831421  0.447253   0.71238863]
 [0.45246387 0.06598949 0.77288103]], shape=(4, 3), dtype=float32)


### **Shuffling the order of tensor**

---


In [13]:
# Global level seed (using set_seed)
tf.random.set_seed(42) # if we set seed, the output won't change on running multiple times

# Operational level seed (used as parameter)
x=tf.random.shuffle(tensor1,seed=42) 
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.29604465, -0.21134205],
       [ 0.01063002,  1.5165398 ],
       [ 0.27305737, -0.29925638]], dtype=float32)>

### **Tensor attributes**

---




*   Shape of a tensor (length of each dimension that a tensor has)
*   Rank of a tensor (The number of dimensions a tensor has)
*   Axis or dimension of a tensor
*   Size of a tensor (total number of items in it)
*   Data type of each element present in the tensor





In [21]:
# Create a rank 4 tensor
tensor = tf.zeros(shape=[3,4,3,5])
tensor

<tf.Tensor: shape=(3, 4, 3, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0.,

In [23]:
tensor.shape,tensor.dtype,tensor.ndim,tf.size(tensor) # shape, data type, rank, size respectively

(TensorShape([3, 4, 3, 5]),
 tf.float32,
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=180>)

In [26]:
tensor[:2,:,:,:3] # slice for each dimension are seperated by commas (left->right higher->lower dimension)
# [left_index:right_index,left_index:right_index,left_index:right_index,left_index:right_index]

<tf.Tensor: shape=(2, 4, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

**Converting rank 2 tensor to a rank 3 tensor**

---


In [27]:
rank2_tensor = tf.constant([[1,2,3],[6,7,8]])
rank2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [6, 7, 8]], dtype=int32)>

In [29]:
# Method 1
rank3_tensor=rank2_tensor[...,tf.newaxis] # add a new axis with all elements remaining same and only changing the shape
rank3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[6],
        [7],
        [8]]], dtype=int32)>

In [34]:
# Method 2
rank3_tensor=tf.expand_dims(rank2_tensor,axis=0) # add a new axis along the axis mentioned in axis parameter
rank3_tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [6, 7, 8]]], dtype=int32)>

### **Basic mathematical operations**


---



In [39]:
# the math operation will get applied on each element of the tensor
tensor = tf.constant([[1,2,3],[4,5,6]])
print(tensor+10)
print(tensor*10)
print(tensor/10)
print(tensor*tensor) #squares each tensor element

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)


## **Matrix multiplication**


---


> Matrix multiplication is done with **tf.linalg.matmul** or **tf.tensordot** or using `@` operator





In [42]:
tensor1=[[1,2,3],[4,5,6]]
tensor2=[[1,2],[3,4],[5,6]]
ans = tf.linalg.matmul(tensor1,tensor2) # matrix dimensions should be compatible (r*c,c*s)
ans

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

## **Reshaping a tensor, transpose**


---

> Reshaping a tensor is done by **tf.reshape()**



In [45]:
tensor=tf.constant([[1,2,3,4],[12,3,5,6],[7,8,8,10]])
print(tf.reshape(tensor,shape=(2,6)))

# Transpose of a tensor
print(tf.transpose(tensor))

tf.Tensor(
[[ 1  2  3  4 12  3]
 [ 5  6  7  8  8 10]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[ 1 12  7]
 [ 2  3  8]
 [ 3  5  8]
 [ 4  6 10]], shape=(4, 3), dtype=int32)


**Changing data type using tf.cast**

---


In [47]:
new_dtype_tensor = tf.cast(tensor,dtype=tf.float32)
new_dtype_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [12.,  3.,  5.,  6.],
       [ 7.,  8.,  8., 10.]], dtype=float32)>

### **Getting min,max,mean,sum and abs of a tensor**

---

In [49]:
tensor=tf.constant(np.random.randint(-50,50,size=30))
tensor

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([-49,  47, -21, -28, -19,  32,  20,  21,  16,  14, -32, -38, -50,
        -3,  23, -19,  40,   7,  37,  19,  27,  44,   1,  -8,  27, -40,
       -16,  34, -48,  37])>

In [62]:
print("abs: ",tf.abs(tensor).numpy())
print("min: ",tf.reduce_min(tensor).numpy())
print("max: ",tf.reduce_max(tensor).numpy())
print("mean: ",tf.reduce_mean(tensor).numpy())
print("sum: ",tf.reduce_sum(tensor).numpy())

# argmax and argmin return the position of the maximum and minimum elements respectively
print("position of max element:",tf.argmax(tensor).numpy())
print("position of min element:",tf.argmin(tensor).numpy())

abs:  [49 47 21 28 19 32 20 21 16 14 32 38 50  3 23 19 40  7 37 19 27 44  1  8
 27 40 16 34 48 37]
min:  -50
max:  47
mean:  2
sum:  75
position of max element: 1
position of min element: 12


**Finding the variance (tfp.math.reduce_variance())**

In [60]:
variance = tf.math.reduce_variance(tf.cast(tensor,dtype=tf.float32))
print(variance.numpy())

923.85


**Standard deviation using tf.math.reduce_std() (dtype should be float)**

In [56]:
std = tf.math.reduce_std(tf.cast(tensor,dtype=tf.float32))
print(std.numpy())

30.394901


**Squeezing a tensor**

---

> Remove all the singular dimensions in the tensor



In [64]:
tensor=tf.constant(tf.random.normal(shape=[20]),shape=(1,1,1,20))
tensor,tensor.shape

(<tf.Tensor: shape=(1, 1, 1, 20), dtype=float32, numpy=
 array([[[[ 8.4224582e-02, -8.6090374e-01,  3.7812304e-01,
           -5.1962738e-03, -4.9453196e-01,  6.1781919e-01,
           -3.3082047e-01, -1.3840806e-03, -4.2373410e-01,
           -1.3872087e+00, -1.5488191e+00, -5.3198391e-01,
           -4.4756433e-01, -2.0115814e+00, -5.7926011e-01,
            5.7938927e-01,  1.3041967e+00,  6.7720258e-01,
           -7.4587613e-01,  1.0378964e+00]]]], dtype=float32)>,
 TensorShape([1, 1, 1, 20]))

In [67]:
tensor=tf.squeeze(tensor)
tensor,tensor.shape

(<tf.Tensor: shape=(20,), dtype=float32, numpy=
 array([ 8.4224582e-02, -8.6090374e-01,  3.7812304e-01, -5.1962738e-03,
        -4.9453196e-01,  6.1781919e-01, -3.3082047e-01, -1.3840806e-03,
        -4.2373410e-01, -1.3872087e+00, -1.5488191e+00, -5.3198391e-01,
        -4.4756433e-01, -2.0115814e+00, -5.7926011e-01,  5.7938927e-01,
         1.3041967e+00,  6.7720258e-01, -7.4587613e-01,  1.0378964e+00],
       dtype=float32)>, TensorShape([20]))

## **One hot encoding of tensors**

---
> This can be done tf.one_hot(list,depth) and also using pd.get_dummies()

In [74]:
arr=[0,1,2,3,4] # a list of indices
tensor=tf.one_hot(arr,depth=4)
tensor

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>